### ISSUE TITLE
Invalid program composite

### ISSUE THREAD

**Issue by enagimintas** [Septonious/Prismarine-Shader#2]
White world lol, that is befor my pow changes, I will test previous commits to
![2022-01-01_12 59 03](https://user-images.githubusercontent.com/81624519/147848209-fa47e928-a198-4ffe-bd09-f3db9a07a6f9.png)

**Comment by enagimintas** [comment]
Testing if it IntegratedEmission commit

**Comment by enagimintas** [comment]
it is after first code cleanup

**Comment by Septonious** [comment]
#bugs-and-suggestions in my discord server
i need latest.log

**Comment by enagimintas** [comment]
water fixed, land - no

**Comment by enagimintas** [comment]
![2022-01-01_13 21 51](https://user-images.githubusercontent.com/81624519/147848506-87d83281-5dca-4caa-a150-d46ffddfb3e4.png)
no

**Comment by enagimintas** [comment]
oh wait
that is just sun being atomic bomb

**Comment by enagimintas** [comment]
![2022-01-01_13 24 17](https://user-images.githubusercontent.com/81624519/147848524-5ce156f8-2030-4be1-9b03-9895bb64cb79.png)
NOISYYYY

**Comment by enagimintas** [comment]
I guess this is closed, that is the other issue
